### ISSUE TITLE
Add method update partial index

### ISSUE THREAD

**Issue by chutiphon-k** [elastic/app-search-node#16]
I see in the documentation there is update partial but in `@elastic/app-search-node` there is no this method.

version: `7.6.0`

https://swiftype.com/documentation/app-search/api/documents#partial

<img width="951" alt="Screen Shot 2020-03-28 at 4 37 03 PM" src="https://user-images.githubusercontent.com/8829331/77820223-3bcf9a80-7113-11ea-9db2-0e258f48ef55.png">

`appSearch.js`
```js
/**
   * Partial update a batch of documents.
   *
   * @param {String} engineName unique Engine name
   * @param {Array<Object>} documents Array of document objects to be updated.
   * @returns {Promise<Array<Object>>} a Promise that returns a result {Object} when resolved, otherwise throws an Error.
   */
  updateDocuments(engineName, documents) {
    return this.client.patch(`engines/${encodeURIComponent(engineName)}/documents`, documents)
  }
```

`client.js`
```js
  patch(path, params) {
    return this._jsonRequest('PATCH', path, params)
  }
```

**Comment by JasonStoltz** [comment]
@chutiphon-k I have a PR to add this to 7.7
