### ISSUE TITLE
Lates NPM version does not match repository

### ISSUE THREAD

**Issue by b0123498765** [elastic/app-search-node#19]
When installing the latest version from npm `7.6.0`, it's missing the latest functions like `listDocuments`.

If copying the `/lib` folder from the repo they work.

**Comment by durdenx** [comment]
Same for me. Release needed.

**Comment by ElGreetly** [comment]
Same here

**Comment by ElGreetly** [comment]
It's updated the issue should be closed I think

**Comment by JasonStoltz** [comment]
Thank you for calling this out 👍
