### ISSUE TITLE
Corrects redundant variable nomenclature

### ISSUE THREAD

**Issue by robertosousa1** [elastic/app-search-node#32]
In the file "test/test.js" in the describe #multiSearch function the nomenclature "res" is used repeatedly, which causes confusion in the indentation, due to the declaration in the upper scope.

A simple and quick solution would be to implement the following code:

> CURRENT:

.then((resp) => { assert.deepEqual(resp.map(res => res.results.map(res => res.title.raw)), [[

> SUGGESTION:

.then((response) => { assert.deepEqual(response.map(resp => resp.results.map(res => res.title.raw)), [[

Or we can even rename the variables in more detail within each scope.

**Comment by JasonStoltz** [comment]
Ah, that's interesting. Feel free to submit a PR to clean that up.

**Comment by robertosousa1** [comment]
Hi Jason,

Grateful for the answer.

I tried to commit to a local branch that I created for the adjustment but I have received "The requested URL returned error: 403".

Should I do something before?

**Comment by JasonStoltz** [comment]
Hey @robertosousa1,

I'm actually thinking that a PR to simply fix variable naming may not make a worthwhile PR at this point. Not that it is not important to have good, clean, readable code, but rather accepting a PR just to rename variables may introduce unnecessary risk.

Thanks you for pointing this out! I'll keep this issue open, as we could address this as part of a separate PR in the future.

**Comment by robertosousa1** [comment]
Hi @JasonStoltz.

As the issue is open, I took the liberty of creating a PR to check the code integrity with CircleCI tests, based on the tests, everything looks good.

If you believe you have no risks, PR can follow.

Any eventuality, I make myself available too.

**Comment by JasonStoltz** [comment]
Closing this issue as mentioned here: https://github.com/elastic/app-search-node/pull/42
