### ISSUE TITLE
Please add search_settings endpoint to api client

### ISSUE THREAD

**Issue by govindrai** [elastic/app-search-node#36]
Feature request: We have many environments, and we want to be able to easily create engines and tweak their settings programmatically on various environments without needing to log in. I know I can use the low level api directly but this would be a lot more consistent. Thanks!

**Comment by JasonStoltz** [comment]
Hey @govindrai. We're planning work on a new and improved client that will ultimately replace this one. No firm dates or anything yet, but for that reason, and also that all APIs are callable via the low-level API, we will not be adding additional endpoints to this client. Sorry if that causes any inconvenience for you!
