### ISSUE TITLE
Feature Requests: Add support for retries and custom http agent

### ISSUE THREAD

**Issue by govindrai** [elastic/app-search-node#40]
It would be nice if retries could be configured and a sensible default set (sometimes I hit a bad gateway)

Also it would be nice if there was an ability to set a custom http agent, but one with with a sensible max connections and keep alive timeout so that connections can be reused server side. Currently every request is made over a brand new connection and incurs expensive handshake costs.

**Comment by JasonStoltz** [comment]
We're working on a fresh new client to replace this client that should support all of these features.
