### ISSUE TITLE
Is there a way to return a calculated distance with App Search?

### ISSUE THREAD

**Issue by ajlamarc** [elastic/app-search-node#41]
Elasticsearch allows script_fields but I don't think that extends to app search.  I want to show the distance between two users without returning the exact coordinates to the client side, is this possible? 

```
{
    "query": "",
    "filters": {
        "location": {
            "center": "a, b",
            "distance": 1000,
            "unit": "mi"
        }
    }
```

My current code filters by location but does not return the distance in the response.

**Comment by JasonStoltz** [comment]
Unfortunately, there's no way to do this at this time. I'm happy to pass this along as feedback though, it would be value!
