### ISSUE TITLE
Syntax for match/term queries

### ISSUE THREAD

**Issue by ctklainow** [elastic/app-search-node#45]
Hi, is it possible to perform match queries using this library?

```
{
  "query": {
    "match": {
      "full_text": "Blue Tea"
    }
  }
}
```
OR

```
{
  "query": {
    "term": {
      "product_type": {
        "value": "Blue Tea",
      }
    }
  }
}
```

I'd like to get 2 separate results for 'Blue Tea' and 'Red Tea' for example, and I'm not sure it's possible with the example in the documentation.

Thanks!

**Comment by JasonStoltz** [comment]
I'm not sure you could do exactly what you're looking for.

You can provide exactly one query string: https://www.elastic.co/guide/en/app-search/current/search.html

Within that query string you can use the lucene 'OR' syntax that could help.

You can specify which fields should be searched with that query string: https://www.elastic.co/guide/en/app-search/current/search-fields-weights.html

And lastly, you can apply filters when necessary: https://www.elastic.co/guide/en/app-search/current/filters.html#filters-value-filters.

Just pointing out a few different tools in the toolbox. Hopefully they can help guide you.
